## this program controls the quicsyn to generate some frequency
## and to control the SA to read the signal that is generated by the quuicsyn

import numpy as np
from tqdm import tqdm

# from config import *
from sa import SpectrumAnalyzer
# from instruments.quicsyn import QuicSyn
import json

sa = SpectrumAnalyzer()
# RBW 10kHz, VBW 10kHz
sa.setup(10e3, 10e3)
# 20dBm reference power
sa.set_power(20)

# 

# Sweep the frequency from 600MHz to 7.5GHz with 1000 points
freq_sweep = np.linspace(600e6, 7.5e9, 1000)
results = np.zeros_like(freq_sweep)

for idx, freq in enumerate(tqdm(freq_sweep)):

    # Grab the maximum power in a 1MHz span about the center frequency
    results[idx] = sa.scan(freq, 1e6).max()


sa.close()

with open("quicsyn_profile.json", "w+") as w:
    w.write(json.dumps(
        np.array([freq_sweep, results]).tolist()
    ))

